---
- hosts: all
  tasks:
  - name: modify ifnames=0 if exist
    replace:
      path: /etc/default/grub
      regexp: '(net[.]ifnames=\d+)'
      replace: 'net.ifnames=0'

  - name: add ifnames if not exist
    replace:
      path: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX((?!net[.]ifnames=\d).)*)\"$'
      replace: '\g<1> net.ifnames=0"'

  - name: modify biosdevname if exist
    replace:
      path: /etc/default/grub
      regexp: '(biosdevname=\d+)'
      replace: 'biosdevname=0'

  - name: add biosdevname if not exist
    replace:
      path: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX((?!biosdevname=\d).)*)\"$'
      replace: '\g<1> biosdevname=0"'

  - name: grub2-mkconfig
    command: grub2-mkconfig

