---
# tasks for vsftpd
- name: Instal vsftpd
  yum:
    name: vsftpd
    state: latest

- name: pub directory
  file:
    path: "{{ ftp_pub_dir }}"
    state: directory
    group: root
    owner: root
    mode: '755'
    setype: public_content_t

- name: pub upload directory
  file:
    path: '{{ ftp_pub_dir }}/upload'
    state: directory
    group: root
    mode: '777'
    owner: root
    setype: public_content_rw_t

#- name: SELinux policy for anon write
#  seboolean:
#    name: allow_ftpd_anon_write
#    state: yes
#    persistent: yes

- name: SELinux policy for anon write
  seboolean:
    name: allow_ftpd_full_access
    state: yes
    persistent: yes


- name: Start service vsftpd
  service:
    name: vsftpd
    state: started
  notify: open ftp

- name: Config file
  template:
    src: vsftpd.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: restart ftp

